### ISSUE TITLE
Eu, como usuário, gostaria de visualizar itens como uma checklist para marcar o que foi feito

### ISSUE THREAD

**Issue by lucaaas** [lucaaas/to-do-list#2]
### Critérios de aceitação

- [x] É possível visualizar os itens não concluídos
- [x] É possível marcar ou desmarcar um item como concluído
- [x] Todos os itens concluídos são mostrados abaixo dos não concluídos
- [x] É possível colapsar itens concluídos
